=== AlbertoCastelp/BBDD-PER5784-2223/Tema_2/PedroDeseado/PizzaSchema.xsd
<?xml version = "1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault = "qualified">
    <xsd:element name = "pizzas">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name = "pizza" maxOccurs= "unbounded">
                    <xsd:complexType>
                        <xsd:sequence minOccurs = "1" maxOccurs = "5">
                            <xsd:element ref = "ingrediente"/>
                        </xsd:sequence>
                        <xsd:attribute name = "nombre" use = "required" type = "xsd:string"/>
                        <xsd:attribute name = "precio" use = "required" type = "xsd:decimal"/>
                        <xsd:attribute name = "vegana" use = "required" type = "xsd:boolean"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="ingrediente">
        <xsd:complexType>            
            <xsd:attribute name = "nombre" use = "required" type = "xsd:string"/>       
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== AlbertoCastelp/BBDD-PER5784-2223/Tema_2/PedroDeseado/PizzaCatalog.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<pizzas 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="./PizzaSchema.xsd">
    <pizza nombre = "Margarita" precio = "19.95" vegana = "false">
        <ingrediente nombre = "mozarella"></ingrediente>
        <ingrediente nombre = "albahaca"></ingrediente>
        <ingrediente nombre = "tomate"></ingrediente>
        <ingrediente nombre = "sal"></ingrediente>
        <ingrediente nombre = "aceite"></ingrediente>                     
    </pizza>
    <pizza nombre = "Cuatro Quesos" precio = "18.95" vegana = "false">
        <ingrediente nombre = "mozarella"></ingrediente>
        <ingrediente nombre = "azul"></ingrediente>
        <ingrediente nombre = "gorgonzola"></ingrediente>
        <ingrediente nombre = "roquefort"></ingrediente>
        <ingrediente nombre = "aceite"></ingrediente>
    </pizza>
    <pizza nombre = "Veggie" precio = "16.95" vegana = "true">
        <ingrediente nombre = "cebolla"></ingrediente>
        <ingrediente nombre = "maiz"></ingrediente>
        <ingrediente nombre = "pimiento verde"></ingrediente>        
    </pizza>
</pizzas>
