=== AlbertoCastelp/BBDD-PER5784-2223/Tema_2/Julian Carrascosa Cosano/Pizzas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Pizzas">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="Pizza" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Ingrediente" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="nombre" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nombre" use="required" />
                        <xs:attribute name="precio" type="xs:integer" use="required" />
                        <xs:attribute name="vegana" type="xs:boolean" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AlbertoCastelp/BBDD-PER5784-2223/Tema_2/Julian Carrascosa Cosano/Pizzas.xml
<?xml version="1.0" encoding="UTF-8"?>
<Pizzas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Pizzas.xsd">
<Pizza nombre="Margarita" precio="10" vegana="true">
    <Ingrediente nombre= "Tomate"></Ingrediente>
    <Ingrediente nombre= "Oregano"></Ingrediente>
    <Ingrediente nombre= "Pimienta Negra"></Ingrediente>
</Pizza>
<Pizza nombre="Cuatro Estaciones" precio="15" vegana="false">
    <Ingrediente nombre= "Tomate"></Ingrediente>
    <Ingrediente nombre= "Champiñon"></Ingrediente>
    <Ingrediente nombre= "Aceitunas"></Ingrediente>
    <Ingrediente nombre= "Mozzarela"></Ingrediente>
</Pizza>
​<Pizza nombre="Cuatro Quesos" precio="20" vegana="false">
    <Ingrediente nombre= "Roquefort"></Ingrediente>
    <Ingrediente nombre= "Gorgonzola"></Ingrediente>
    <Ingrediente nombre= "Provolone"></Ingrediente>
    <Ingrediente nombre= "Parmesano"></Ingrediente>
</Pizza>
​<Pizza nombre="Diavola" precio="25" vegana="false">
    <Ingrediente nombre= "Mozzarella"></Ingrediente>
    <Ingrediente nombre= "Pepperoni"></Ingrediente>
    <Ingrediente nombre= "Carne"></Ingrediente> 
</Pizza>
</Pizzas>
